### ISSUE TITLE
ECONNREFUSED when using URL without https/http prefix

### ISSUE THREAD

**Issue by JohannesLamberts** [jfrog/jfrog-client-js#40]
Trying the client with just the Domain lead to an Error thrown by axios "ECONNREFUSED 127.0.0.1:80".

Only after finding https://stackoverflow.com/questions/60557433/axios-request-error-connect-econnrefused-127-0-0-180 I and adding the "http://" or "https://" prefix, it worked.

I suggest to simply adjust the README with "platformUrl: 'https://my-platform-url.jfrog.io/',"

**Comment by yahavi** [comment]
@JohannesLamberts,
Thanks for letting us know.
Following your feedback, we merged https://github.com/jfrog/jfrog-client-js/pull/41.
